### ISSUE TITLE
Uncorrectly calculating compressed ECPoint.

### ISSUE THREAD

**Issue by NicolasDorier** [darkwallet/darkwallet#132] opened 2014-05-26 17:58 UTC
At https://github.com/dabura667/electrum/blob/StealthAddressSend/lib/bitcoin.py#L619
The encoding of the point is not correct (https://bitcointalk.org/index.php?topic=615664.msg6953130#msg6953130)

**Comment by dabura667** [comment] 2014-05-27 15:25
I think you mean this?

https://github.com/darkwallet/darkwallet/blob/develop/js/util/stealth.js#L42

**Comment by NicolasDorier** [comment] 2014-05-27 15:32
oups yes that's what I meant.

**Comment by caedesvvv** [comment] 2014-05-28 08:50
duplicate of #131

**Closed as completed by caedesvvv** 2014-05-28 08:50 UTC
