### ISSUE TITLE
Can't rename pockets

### ISSUE THREAD

**Issue by JPCrypto** [darkwallet/darkwallet#152] opened 2014-06-23 09:26 UTC
I've just started using DW 0.5.0. I restored from a backup and want to rename my pockets back to the way I like them. I click on "Rename" and although I can type into the resultant field I am unable to save the new name.

**Comment by caedesvvv** [comment] 2014-06-23 09:51
Can you show the error from the javascript console?

https://wiki.unsystem.net/en/index.php/DarkWallet/Debug

Otherwise I'll try to reproduce by loading from a backup but I can rename in my wallet.

**Comment by JPCrypto** [comment] 2014-06-23 10:00
Actually I got it to work. I just went into Extensions and did a re-load. I was able to rename wallets after performing that step. Sorry for the confusion!

**Comment by caedesvvv** [comment] 2014-06-26 18:43
closing since it was probably an issue of not restarting the backend after upgrade.

**Closed as completed by caedesvvv** 2014-06-26 18:43 UTC
Labels: frontend, critical
