### ISSUE TITLE
rebroadcasting stuck transaction

### ISSUE THREAD

**Issue by millsdmb** [darkwallet/darkwallet#211] opened 2015-01-10 00:14 UTC
How is this done? I'm running the latest GIT, and still getting transactions stuck. I see code was added but for the life of me cant see it in the GUI.

I realize I could export the private keys but it is becoming tiresome (and I dislike blockchain.info)

Thanks in advance.

**Comment by veox** [comment] 2015-01-10 01:30
It should be available in the drop-down menu for a particular transaction on the "History" tab of a pocket.

Does this transaction show in the tx list?

I've been trying to reproduce this issue, since many people seem to be having it. But since it's subject to backend broadcaster instability, it's hardly repeatable.

**Comment by millsdmb** [comment] 2015-01-10 01:32
not seeing it. Perhaps the wallet does not think it has failed? See zero confirmations in the screen shot. Hope I can help.

![image](https://cloud.githubusercontent.com/assets/7471116/5689916/9c4446bc-983e-11e4-8980-1a0c14cf74b4.png)

**Comment by caedesvvv** [comment] 2015-01-10 03:19
it should allow cancelling if you're sending it. The option is called "Rebroadcast" or "Clear transaction" (depending what you want to do)
it should show in the menu below what you show there.

**Comment by millsdmb** [comment] 2015-01-10 14:37
the screen shot shows all the options available to me for the respective stuck transaction. It may look cut off to preserve my tx-out privacy, but all the options available to me are there. I don't see either Rebroadcast or Clerar anywhere. Any other tips?

![image](https://cloud.githubusercontent.com/assets/7471116/5691939/c3a60f6a-98ac-11e4-80b2-631799578f8c.png)

**Comment by veox** [comment] 2015-01-10 18:18
Broadcaster might be down now - I've managed to get a tx stuck. I haven't restarted the browser yet, the two menu items are present for me.

From the [commit that added manual rebroadcasting](https://github.com/darkwallet/darkwallet/commit/65f55cb76ff70d8c4d6abd63410de64cb3be891b) (EDIT: [current](https://github.com/darkwallet/darkwallet/blob/develop/src/html/wallet/history.html#L68)), there are two conditions it checks:

`!currentRow.height && currentRow.inMine`

For this stuck tx, `height` is `0`, `inMine` is `true`, so it displays properly in the list.

@millsdmb, you can verify if this is true for you, too, by doing

(EDIT: code wrong, see my next comment)

``` js
var DarkWallet = require("darkwallet");
var identity = DarkWallet.getIdentity();
identity.history.history[N].height
identity.history.history[N].inMine
```

in the [debug console](https://wiki.unsystem.net/en/index.php/DarkWallet/Debug), where `N` is most probably `identity.history.history.length - 1`, if that's the last transaction you tried to send.

Once we determine which of the two properties is wrong, we can delve into what actually happened.

Using latest `0.7.0-54-g86af84a` on mainnet.

**Comment by millsdmb** [comment] 2015-01-10 19:07
![image](https://cloud.githubusercontent.com/assets/7471116/5692798/46d17418-98d2-11e4-9120-755757e2f5c5.png)

my latest is 86af84a, mainnet

**Comment by veox** [comment] 2015-01-12 18:09
I've restarted the browser, and it was still possible for me to remove or rebroadcast this "stuck" transaction. I guess OP stumbled onto some rare edge case. :/

---

@millsdmb Sorry, I was wrong - the transactions aren't ordered by creation time, so that was probably the wrong tx.

To find it, you'll have to do something like

``` js
function foobar(tx) { return tx.hash == 'TXHASH'; }
identity.history.history.filter(foobar)[0].height
identity.history.history.filter(foobar)[0].inMine
```

where `TXHASH` you can get by right-clicking in the UI and choosing "Copy hash".

Also, just in case you want your funds back already: to rebroadcast this tx elsewhere, you can always use

``` js
identity.txdb.transactions['TXHASH'][0]
```

This will give you the tx you can push to any node. Remove the trailing `[0]` to see a few more details on the tx.

But please, post the values of `height` and `inMine` first.

**Comment by caedesvvv** [comment] 2015-01-24 04:58
@millsdmb, do you still have the issue?

**Comment by JasonThePM** [comment] 2015-02-04 15:17
Maybe he doesn't, but I do. @caedesvvv

**Comment by caedesvvv** [comment] 2016-01-27 12:49
Issues broadcasting or rebroadcasting have probably been issues with the broadcaster. Closing since this is not specifically a wallet issue, also we're working on the backend so it should be more stable and also easier to install (so more servers).

**Closed as completed by caedesvvv** 2016-01-27 12:49 UTC
