### ISSUE TITLE
Sending from "Any" address fails

### ISSUE THREAD

**Issue by amingilani** [darkwallet/darkwallet#171] opened 2014-08-10 12:12 UTC
You have to manually select which pocket you're sending funds from. the "Any" option says that you have no coins.

**Comment by caedesvvv** [comment] 2014-09-17 18:32
duplicate of #116

**Closed as completed by caedesvvv** 2014-09-17 18:32 UTC

**Comment by amingilani** [comment] 2014-09-17 23:49
Has this issue been fixed? The last one and this one are both missing merge references!

**Comment by caedesvvv** [comment] 2014-09-18 00:24
no it's not fixed yet, but this is a duplicate of #116 which is open, you can follow the issue there. thanks!
