### ISSUE TITLE
Suggestion: Making unconfirmed / confirmed balances more user friendly.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#88] opened 2014-05-06 06:45 UTC
![capture](https://cloud.githubusercontent.com/assets/6586275/2886530/b9384914-d4e7-11e3-9977-ee0d46583636.PNG)

I understand that currently the stance of this software is for privacy inclined Bitcoin Power Users.

But I still think even the beginner-mid level experience Bitcoin users will be slightly confused by this way of showing. (if they do not fully understand fully using outputs + change addresses)

I think that if I didn't understand change and using up inputs completely, I would see -1 and say "but I only sent 0.5 BTC!!! I lost my money!"

**Current:**
0 BTC (0.00 $) -1 BTC (-430.75 $)

**Suggested:**
Spendable: 0 BTC (0.00 $)
Locked: 0.5 BTC (215.38 $)
Unconfirmed Spent: -0.5 BTC (-215.38 $)

**When above confirms and no more pending transactions:**
Spendable: 0.5 BTC (215.38 $)

**_(Locked and Unconfirmed Spent disappear)**_

**When unconfirmed received extra 0.3 BTC:**
Spendable: 0.5 BTC (215.38 $)
Unconfirmed Received: 0.3 BTC (129.23 $)

**Then when that confirms:**
Spendable: 0.8 BTC (344.60 $)

**Note: Unconfirmed spent will include miner's fee.**

Maybe creating separate lines is not optimal... but I think the way unconfirmed is shown will be confusing for beginner-mid level Bitcoiners.

Also, maybe a "?" link next to Locked line when shown that shows popup saying "When you spend Bitcoins, you must spend what is called an "output" completely, and must wait until the transaction using that output confirms before using it again.

**Comment by caedesvvv** [comment] 2014-05-06 11:04
We have already reworked this in git a bit to make it more intuitive and also allowing spending unconfirmed change (still missing some extra work), but we need to discuss this and your proposal is nice, so let's keep this task to make some decission.

@petertodd was saying we shouldn't allow spending unconfirmed balance even if it's change too.

**Comment by dabura667** [comment] 2014-05-06 12:13
I agree with @petertodd. Allowing spending of unconfirmed change (or unconfirmed received) will lead to people unknowingly (or knowingly) making double spend attempts.

Not to mention the UX for those who don't understand the concept and continue spending change over and over, and the more they spend the less likely it is to get confirmed. Leaving the txes in limbo for extended periods of time. Then if someone requires 6 confirms or something for a service they want... they will be upset to find it might take days...

(It happened to me when I was a noob back in the spending unconfirmed is OK days of Bitcoin-QT)

**Comment by caedesvvv** [comment] 2014-05-08 15:12
ok, just finished a number of updates to make balance show more like you suggest here, though for now i show total unconfirmed, would need some more work to show spent unconfirmed and received unconfirmed separate.

**Comment by caedesvvv** [comment] 2014-05-08 15:12
also we changed back to not allow spending of unconfirmed funds, even change.

**Comment by dabura667** [comment] 2014-05-08 15:50
Thanks a lot, I will test it out.

I'll end up prolly just skimming the commit list anyways, but for future reference could you link the commit(s)? Thanks.

**Comment by caedesvvv** [comment] 2014-05-08 19:09
usually I would do it if it's a one commit fix, but in this case it's a few things and also we changed back and forth between being able to spend unconfirmed to not. :-P

**Comment by caedesvvv** [comment] 2014-05-12 01:45
Ok closing for now since they are already more clear. We can open another task with new instructions if we feel like improving how balance is presented (totally needs improvement but we pretty much did what's specified here.)

**Closed as completed by caedesvvv** 2014-05-12 01:45 UTC
Labels: ui / design, critical
