### ISSUE TITLE
Favicon turns to default when navigating between DW sections

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#99] opened 2014-05-09 13:59 UTC
Does so only for a short time. Minor UI issue.

![cc](https://cloud.githubusercontent.com/assets/7106231/2928838/1b06a31a-d782-11e3-9478-236047d4e089.png)

**Comment by sembrestels** [comment] 2014-05-09 18:02
I can't reproduce it and it is an issue witch we haven't the control. Closing.

**Closed as completed by sembrestels** 2014-05-09 18:02 UTC
Labels: invalid
