### ISSUE TITLE
Pocket address issues

### ISSUE THREAD

**Issue by nicollosoloman** [darkwallet/darkwallet#177] opened 2014-08-30 20:19 UTC
My dark wallet pocket address shows 0 btc, but I have a letter of guarantee and a browseable address search that shows the transaction to indeed have money/btc. Even when I try to make a transfer using the "all" address option, it also says i have 0 btc. How do I resolve this issue?

Thanks,

**Comment by dabura667** [comment] 2014-08-31 02:23
What's a letter of guarantee?

Did someone sell you this? How did they sell it to you? A letter of guarantee sounds fishy...

Does the "browsable address" you have show up in your pocket's addresses list? If so, what does it say next to it?

**Comment by nicollosoloman** [comment] 2014-09-01 19:46
A letter of guarantee is a verification letter with addresses that bitmixer io uses to verify their transactions. When I try to browse the bitcoin address in Dark Wallet I can see the transaction but when i look in my wallet, it says the money isn't there. Does anyone know what I can do to fix this problem? I have the seed

**Comment by dabura667** [comment] 2014-09-02 10:35
Since you copied the address from Dark Wallet into bitmixer.io, have you restored your wallet at all?

Sometimes when you restore the wallet, sometimes addresses get hidden due to differing generation algos from older versions.

What have you done with your DarkWallet wallet from the time you copied your address to the time when you first noticed your payment wasn't arriving?

**Comment by nicollosoloman** [comment] 2014-09-02 21:11
Thank you for responding. 

I restored the wallet from the seed and when I looked for the address under the "all" button, the address wasn't there. Once I created a new pocket, the address that the bitcoins were sent to, appears labelled as a pocket. But, there is no money in it. I have also tried seed scanning to no avail. What do you recommend?

**Comment by dabura667** [comment] 2014-09-05 17:38
Maybe check out #164 and maybe #175

**Comment by nicollosoloman** [comment] 2014-09-05 21:06
i will try this and let you know. thank you very much

**Comment by nicollosoloman** [comment] 2014-09-05 21:32
This was helpful and led me to this site: 

https://forum.unsystem.net/t/bought-bitcoins-but-they-didnt-arrive-in-my-darkwallet-btc-company-provided-proof-that-the-btc-were-sent-what-do-i-do/287/13

Do you by any chance know how to generate the private keys? i'm a noob and i'm not familiar with sx, brainwallet, and etc. 

Thanks again

**Comment by dabura667** [comment] 2014-09-06 08:30
1. if you are a noob, don't use DarkWallet yet. The alpha version is NOT meant for use by "noobs."
2. if you want your bitcoins back, you're going to have to BECOME familiar with "sx, brainwallet, and etc."
3. Everything you need is explained in the two issues I have shown you. Read them. And when I say read them, I mean READ them. As in, read them until you can comprehend exactly what they are talking about 100%.

Hint: https://github.com/darkwallet/darkwallet/issues/175#issuecomment-52042226

**Comment by nicollosoloman** [comment] 2014-09-07 10:37
Thank you for the advice! i'll let you know how it goes once I comprehend the directions completely

**Comment by caedesvvv** [comment] 2014-09-17 20:25
duplicate of #175

**Closed as completed by caedesvvv** 2014-09-17 20:25 UTC

**Comment by caedesvvv** [comment] 2014-09-17 20:27
The root issue has just been fixed and will add tools both to export privkeys and to access funds on these address (the wallet usually doesn't scan or show this address, but the funds are recoverable) for next release due as soon as we solve these issues.

See https://wiki.unsystem.net/en/index.php/DarkWallet/Alpha5/KnownIssues#Creating_pocket_shows_a_.22pocket.22_address_that_won.27t_show_afterwards or task #175 where we track solving access to funds.

**Comment by nicollosoloman** [comment] 2014-09-18 02:38
thank you
